spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend:
    origin: ${FRONTEND_ORIGIN:http://divvi-production.up.railway.app}
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET:divvi-receipts-joey}
      region: ${AWS_REGION:us-east-1}